histogram
js-tasks-ru/htmlcss-20220414_shymakher pull request #7
Opened 2022-04-26 16:00 UTC by Shymakher

2022-04-26 16:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-27 08:58 UTC, GSemikozov requested changes

2022-04-27 08:58 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  min-width: 9px;
flex-basis: 9px; flex-grow: 1

2022-04-27 08:58 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  position: absolute;
этот элемент не нужно абсолютом, лучше попробуем завернуть элементы верхнего уровня в общий враппер и выравнивать через флексы

2022-04-27 15:14 UTC, Shymakher commented on 04-lection2/01-histogram/histogram.css
> +  position: absolute;
в фигме увидел, что они не на одном уровне, поэтому сделал через абсолют

2022-04-27 20:09 UTC, GSemikozov requested changes

2022-04-27 20:09 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  width: 100%;
вот это тогда лишнее

2022-04-27 20:09 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  background-color: #4263eb;
цвет заберем из переменной

2022-04-27 20:09 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  background-color: #4263eb;
и выше тоже

2022-04-27 20:09 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__view-all {
если не на одном уровне, то можно подравняться через padding или margin )

2022-04-28 08:43 UTC, Shymakher commented on 04-lection2/01-histogram/histogram.css
> +  width: 100%;
width: 100% - забыл удалить

2022-04-28 08:46 UTC, Shymakher commented on 04-lection2/01-histogram/histogram.css
> +.histogram__view-all {
1. как тогда знать, когда лучше подравнять через padding или margin, а когда в абсолюте поставить?
2. когда ровняешь через padding или margin, то весь верхний блок (Total orders и View All) отступает на тоже значения padding или margin

2022-04-28 16:27 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__view-all {
1. в целом мы видем что элемент ссылка расположен по сетке (одинаковые отступы родителя одинаковы образом смещают элемент от своих границ. Единственное - у самой ссылки есть доп отступ сверху)
2. отступ задается прямо на ссылке и у ссылки inline-block?

2022-05-03 14:25 UTC, Shymakher commented on 04-lection2/01-histogram/histogram.css
> +.histogram__view-all {
1. за счет доп отступа сверху нужно делать меньше марджин .histogram__header
2. с отступом так и сделал, но это у меня кнопка, а не ссылка

2022-05-03 21:06 UTC, GSemikozov approved these changes

2022-05-03 21:06 UTC, merged