tooltip
js-tasks-ru/htmlcss-20220414_shymakher pull request #8
Opened 2022-04-26 17:47 UTC by Shymakher

2022-04-26 17:48 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-27 08:59 UTC, GSemikozov requested changes

2022-04-27 08:59 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.content {
вспомогательные, глобальные и любые другие стили которые не относятся к текущему компоненты в его файле стилей не размещаем)
конкретно .content можно разместить в теге style хтмл страницы

2022-04-27 08:59 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +  position: relative;
inline-block!

2022-04-27 08:59 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +  background: #4263eb;
не забываем про переменные

2022-04-27 14:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-27 15:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-27 15:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-27 15:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-27 15:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-27 15:25 UTC, Shymakher commented on 05-lection3/01-tooltip/tooltip.css
> +  position: relative;
display: inline-block - это чтобы сам тултип не занимал всю ширину контента?

2022-04-27 15:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-27 20:09 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +  position: relative;
ага

2022-04-27 20:11 UTC, GSemikozov requested changes

2022-04-27 20:11 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +  bottom: 130%;
оч не универсально, если поменяет размеры иконки  - например увеличим, - то всплывашка улетит наверх)
лучше завязываться на 100% и дальше приплюсовывать сколько надо в пикселях (calc(100% + 8px))

2022-04-28 10:01 UTC, Shymakher commented on 05-lection3/01-tooltip/tooltip.css
> +  bottom: 130%;
согласен, так и сделаю)

2022-04-28 16:28 UTC, GSemikozov approved these changes

2022-04-28 16:29 UTC, merged