Modal
js-tasks-ru/htmlcss-20220414_shymakher pull request #9
Opened 2022-04-27 15:37 UTC by Shymakher

2022-04-27 15:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-27 20:13 UTC, GSemikozov requested changes

2022-04-27 20:13 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  margin: -8px;
это потому, что у body margin 8px? лучше в сбросах обнулить

2022-04-27 20:13 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__overlay {
можно обойтись без него и задать фон сразу в .modal  через rgba

2022-04-28 08:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-28 09:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-28 10:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-28 10:16 UTC, Shymakher commented on 05-lection3/02-modal/modal.css
> +.modal__overlay {
ага, вместе с опасити в rgba добавить.
есть ли возможность отменить опасити для дочернего .modal__content-wrap, когда задаешь его в родителе .modal?

2022-04-28 10:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-28 16:29 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__overlay {
нет, с опасити так не сработает)

2022-04-28 16:29 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  margin: -8px;
да?)

2022-05-01 15:52 UTC, Shymakher commented on 05-lection3/02-modal/modal.css
> +  margin: -8px;
полюбому)

2022-05-02 21:25 UTC, GSemikozov requested changes

2022-05-02 21:25 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button-close {
.modal__button-close

2022-05-03 06:56 UTC, Shymakher commented on 05-lection3/02-modal/modal.css
> +.button-close {
согласен, пропустил

2022-05-03 21:06 UTC, GSemikozov approved these changes

2022-05-03 21:06 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-06-06 13:56 UTC, GSemikozov approved these changes

2022-06-06 13:56 UTC, merged